### ISSUE TITLE
Phantom issue: delete all carousel image, navigate through url

### ISSUE THREAD

**Issue by deepakshrma** [deepakshrma/peoplePlugin#11]
Step to reproduce:
1. add carousel image
2. delete all carousel images
3. click on design tab and return to home tab.

![phantom issue](https://cloud.githubusercontent.com/assets/7682731/9047596/8e6ce4b8-3a50-11e5-82c8-a2f7b7421361.png)

**Comment by vineetasharma** [comment]
Fixed the issue, Please check it.
