### ISSUE TITLE
Item List Does Not Reflect The Mockup

### ISSUE THREAD

**Issue by ianblair44** [deepakshrma/peoplePlugin#23]
Make sure the icons are just like the mockup. They are not far enough to the right. 

![screen shot 2015-08-05 at 9 56 54 am](https://cloud.githubusercontent.com/assets/2794086/9092002/56b147c2-3b58-11e5-9df9-419611274202.png)

**Comment by deepakshrma** [comment]
Fixed with https://github.com/deepakshrma/peoplePlugin/issues/19
