### ISSUE TITLE
Widget Item List

### ISSUE THREAD

**Issue by ianblair44** [deepakshrma/peoplePlugin#24]
For nathan keating, there is no image so there shouldn't be a thumbnail. the text should be left aligned when the thumbnail is gone. 

Ian Blair - the image is the wrong dimensions. See the mockup,  use CSS to force the proper dimensions. The image will end up being cropped. Make sure to take the center of the photo. 

![screen shot 2015-08-05 at 9 57 36 am](https://cloud.githubusercontent.com/assets/2794086/9092020/700f2a54-3b58-11e5-80f2-f4559d1dc14f.png)

**Comment by vineetasharma** [comment]
Fixed first part of the issue.
