### ISSUE TITLE
Not using image resize function. 

### ISSUE THREAD

**Issue by ianblair44** [deepakshrma/peoplePlugin#28]
https://github.com/BuildFire/sdk/wiki/How-to-use-ImageLib

Scroll to the bottom of the page and make sure we use this to ensure we are always getting the fastest load times.

**Comment by sakshityagi** [comment]
Hey Ian, in issue https://github.com/deepakshrma/peoplePlugin/issues/24 we have to force the image dimension using css and show cropped image. I have done it using css and buildfire.imageLib.cropImage() and it is working fine. I don't understand where do I need to use resize() method?

**Comment by sakshityagi** [comment]
Done. please review.
Now small images are being loaded in case of thumbnails. Also fixed carousel images image dimension issue.
