### ISSUE TITLE
In correct implementation of social link.

### ISSUE THREAD

**Issue by deepakshrma** [deepakshrma/peoplePlugin#29]
refer to https://github.com/BuildFire/sdk/wiki/How-to-use-action-Items#buildfireactionitemsshowdialog-actionitem-optional--options-optional--callback

``` js
{
title: "build fire",
url: "https://www.facebook.com/buildfireapps",
action: "linkToWeb",
openIn: "browser",
actionName: "Link to Web Content"
}
```

**Comment by sakshityagi** [comment]
This task is still not done. Task number in burn down sheet : BF-018. WIll work on it today.

**Comment by deepakshrma** [comment]
![svae](https://cloud.githubusercontent.com/assets/7682731/9107508/5918c9f2-3c45-11e5-8a37-a7168e056e3e.png)

**Comment by sakshityagi** [comment]
This issue is related to the actionItem api. I have logged it on github.
https://github.com/BuildFire/sdk/issues/59

**Comment by deepakshrma** [comment]
Error on add link. Remove $$haskey
http://stackoverflow.com/questions/18826320/what-is-the-hashkey-added-to-my-json-stringify-result
![error on save](https://cloud.githubusercontent.com/assets/7682731/9108508/54195b22-3c4c-11e5-870c-34f1199b40fb.png)

**Comment by sakshityagi** [comment]
Cannot reproduce the bug. Please mention steps.
