### ISSUE TITLE
HTML gets messed up on long title length

### ISSUE THREAD

**Issue by sandeepchhapola** [deepakshrma/peoplePlugin#31]
![html massed if title is large](https://cloud.githubusercontent.com/assets/7790671/9107574/e1712092-3c45-11e5-901f-2dd5dbdd9c1b.png)

**Comment by vineetasharma** [comment]
![carousel-images-not-shown-properly](https://cloud.githubusercontent.com/assets/7790663/9130516/2326605e-3d01-11e5-9aa8-701129923c86.png)

**Comment by sakshityagi** [comment]
Done. Please review.
