### ISSUE TITLE
Manual sorting not working in Widget section.

### ISSUE THREAD

**Issue by vineetasharma** [deepakshrma/peoplePlugin#33]
Steps:
1. Select the manual sorting option in content section then people listing gets sorted according to manual sorting but widget section does not reflected.
![manual-sorting-not-working](https://cloud.githubusercontent.com/assets/7790663/9129949/7876df3a-3cfb-11e5-868b-4f432b981aeb.png)

**Comment by sakshityagi** [comment]
Done. Please review.
