### ISSUE TITLE
If background image is added, show it in background of description and people listing in widget section

### ISSUE THREAD

**Issue by sakshityagi** [deepakshrma/peoplePlugin#43]

**Comment by vineetasharma** [comment]
Hi Ian,
I have added the background image in widget section in the following two manners. Please Check these or suggest me for better one.
![background-image-demo2](https://cloud.githubusercontent.com/assets/7790663/9175409/39d5ac7a-3fa3-11e5-8456-1a015856957f.png)
![background-image-demo](https://cloud.githubusercontent.com/assets/7790663/9175412/3df5e78e-3fa3-11e5-9dd0-cae6e6f2f610.png)
