### ISSUE TITLE
Add wysiwyg editor in description, add new item 

### ISSUE THREAD

**Issue by sakshityagi** [deepakshrma/peoplePlugin#47]

**Comment by sakshityagi** [comment]
Ian or Daniel will get back on this with some designs.

**Comment by sakshityagi** [comment]
FYI: https://github.com/BuildFire/sdk/wiki/How-to-use-the-WYSIWYG-editor

**Comment by sakshityagi** [comment]
Waiting for reply on the issue https://github.com/BuildFire/sdk/issues/66

**Comment by deepakshrma** [comment]
@sandeepchhapola how you can say it is completed... i can see
![adadd](https://cloud.githubusercontent.com/assets/7682731/9257209/ff4a14f8-4211-11e5-842d-49e77b73a604.png)
