### ISSUE TITLE
Export CSV : Get all people data from DB.

### ISSUE THREAD

**Issue by vineetasharma** [deepakshrma/peoplePlugin#54]

**Comment by vineetasharma** [comment]
Refer : https://github.com/BuildFire/sdk/issues/68

**Comment by deepakshrma** [comment]
@vineetasharma It seems you have not clear data on export csv button.
Once i have exported it return 3 records. When i click on the  export button(without) refresh. It export 6 record. twice of the previous. Clear data on export click.
