### ISSUE TITLE
Can't edit items

### ISSUE THREAD

**Issue by ianblair44** [deepakshrma/peoplePlugin#55]
I can't click on a person and edit their details.

![screen shot 2015-08-11 at 4 34 43 pm](https://cloud.githubusercontent.com/assets/2794086/9214082/4d8c5cea-404e-11e5-887b-3ba89dca4b4f.png)

**Comment by sakshityagi** [comment]
@ianblair44 . Hey Ian we have fixed this issue, but this was working earlier as we have showed you in demo also. After taking pull some of the functionality got disturbed for some reasons. May be the UI team is working on HTML. This might lead to re-iteration of these kind of issues.

**Comment by ianblair44** [comment]
Alright, well let's get it fixed without breaking the HTML. Also make sure to add an expression to the ng-hide on the no items found div so that it hides when there are items.
