### ISSUE TITLE
Double Entry

### ISSUE THREAD

**Issue by ianblair44** [deepakshrma/peoplePlugin#56]
Somehow on the widget side, you can see that my item is listed twice when on the content side it is only there once. 

![screen shot 2015-08-11 at 4 32 16 pm](https://cloud.githubusercontent.com/assets/2794086/9214095/6ada8ccc-404e-11e5-9c7f-fb9e7eebf140.png)

**Comment by vineetasharma** [comment]
Not able to reproduce the issue.Please mention the required steps.

**Comment by sakshityagi** [comment]
This should be working fine.
