### ISSUE TITLE
Initializing the Plugin

### ISSUE THREAD

**Issue by ianblair44** [deepakshrma/peoplePlugin#57]
When I first started up the widget you can see that there is no default item for sort items. 
![screen shot 2015-08-11 at 4 29 19 pm](https://cloud.githubusercontent.com/assets/2794086/9214114/9a5e2b84-404e-11e5-86d1-599cdadb9841.png)

**Comment by sakshityagi** [comment]
@ianblair44 Do we have any default view for this type of situation when we do not have any data in the plugin? Which default item are we referring here?

**Comment by ianblair44** [comment]
The default value for sort items should be "manual". It shouldn't just show a blank box.

**Comment by sandeepchhapola** [comment]
Please review it.

**Comment by deepakshrma** [comment]
Design layout is not visible.

![dasas](https://cloud.githubusercontent.com/assets/7682731/9222621/e83d95ca-4110-11e5-93da-8b8f276d2fb7.png)

**Comment by ianblair44** [comment]
For design, it should default to the first layout on each one. It shouldn't be a blank box.

**Comment by deepakshrma** [comment]
@ianblair44  Yes! Ian, @sandeepchhapola is  working on it. Let me review it.
