### ISSUE TITLE
Own Carousel Height

### ISSUE THREAD

**Issue by ianblair44** [deepakshrma/peoplePlugin#58]
It should always be a 16:9 aspect ratio. Make sure to calculate the height of the carousel. 

![screen shot 2015-08-11 at 4 31 50 pm](https://cloud.githubusercontent.com/assets/2794086/9214118/aa7c2098-404e-11e5-8301-672c59fcfde1.png)

**Comment by sakshityagi** [comment]
Need to discuss this on call.

**Comment by sakshityagi** [comment]
Done. Please review.
