### ISSUE TITLE
Update people list when CSV imported

### ISSUE THREAD

**Issue by sandeepchhapola** [deepakshrma/peoplePlugin#61]

**Comment by deepakshrma** [comment]
Tested found new issue.. It inserts double of data that exported. refer to pics.

![3](https://cloud.githubusercontent.com/assets/7682731/9243676/252a7688-41b1-11e5-9a0f-493893bdd0e0.png)

![3exprorted](https://cloud.githubusercontent.com/assets/7682731/9243678/2b90a92a-41b1-11e5-964a-22dcaa2110f9.png)

![9records](https://cloud.githubusercontent.com/assets/7682731/9243681/316b48d2-41b1-11e5-999d-6b538f251df9.png)

**Comment by sandeepchhapola** [comment]
Please review it.

**Comment by deepakshrma** [comment]
@sandeepchhapola  still not working :-1:
