### ISSUE TITLE
Loading list and item view.

### ISSUE THREAD

**Issue by ianblair44** [deepakshrma/peoplePlugin#65]
When you are on the list page and click on an item, or you are in an item and go back to the list. The page doesn't load in very smooth. It feels like it is rendering a web page. 

Most people on mobile phone enjoy a very smooth experience. Can we make it so it loads a bit smoother instead of everything flickering in?

**Comment by deepakshrma** [comment]
@ianblair44  Done some changes in new pull request. Check it.
