### ISSUE TITLE
Carousel Image is mandatory

### ISSUE THREAD

**Issue by deepakshrma** [deepakshrma/peoplePlugin#7]
There will be no default image. Dont add image on carousel if user dont add it
![no-default-image-no-carousel](https://cloud.githubusercontent.com/assets/7682731/9047379/3d158f44-3a4f-11e5-9ae8-9b9b8b6e18e6.png)
![atleast one of them is mandatory](https://cloud.githubusercontent.com/assets/7682731/9047432/83c79004-3a4f-11e5-972c-4546c0fa6949.png)

**Comment by sakshityagi** [comment]
Fixed Issue. Please take pull and review.
