### ISSUE TITLE
Issue with widget tab, On every single update/change in add new item page its add new record in widget

### ISSUE THREAD

**Issue by deepakshrma** [deepakshrma/peoplePlugin#9]
![on every update- add new image in widget](https://cloud.githubusercontent.com/assets/7682731/9047505/0c6ad3da-3a50-11e5-987f-5a97820e7cf6.png)

**Comment by sakshityagi** [comment]
This is working fine now. Please review.

**Comment by deepakshrma** [comment]
Now It is not working. 
Steps:
1. Clicked on add new item
2. Fill the data like name
Expected:
It should be there in the list on widget
Actual:
Same result set in widget

**Comment by sakshityagi** [comment]
Waiting for this issue to get fixed.
https://github.com/BuildFire/sdk/issues/51

**Comment by sakshityagi** [comment]
Working fine now.
